# File: .github/workflows/workflow.yml

on: [push]

name: Azure Login

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - uses: azure/login@v1
      env: 
       CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      
      with:
        creds: ${{ env.CREDENTIALS }}
