on: [push]

name: AzureCLISample

jobs:

  build-and-deploy:
    runs-on: windows-latest
    steps:

    - name: Run a script file from my repo
    - run: sh ./github-actions.sh
      shell: pwsh
      
    