on: [push]

name: AzureCLISample

jobs:

  build-and-deploy:
    runs-on: windows-latest
    steps:

    - uses: azure/CLI@v1

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        inlineScript: |
          az account show
          az storage -h