on: [push]

name: AzureCLISample

jobs:

  build-and-deploy:
    runs-on: windows-latest
    steps:
    - name: echo "This is running a script"
      uses: actions/checkout@v2.4.0
    - run: sh ./github-actions.sh
      shell: pwsh
      
    